[package]
name = "python-boilerplate"
version = "1.0.0"
description = "This is boilerplate for Python project"
authors = [ "AlexSergey <gooddev.sergey@gmail.com>",]
license = "MIT"

readme = 'README.md'

python = ["^3.6"]

[dependencies]
better_exceptions = "^0.1.6"